version: "3.8"
services:
  base:
    image: stackhawk/vuln-graphql-ruby
    container_name: gql-ruby
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 9000:3000
    entrypoint:
      - docker-entrypoint.sh
    networks:
      hawknet:
        aliases:
          - gql-ruby
networks:
  hawknet:
    name: hawknet
    ipam:
      driver: default
